package generatedSource.com.tanmoy.mypackage;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.8
 * 2016-11-14T19:44:22.492+05:30
 * Generated source version: 3.1.8
 * 
 */
@WebService(targetNamespace = "http://service/", name = "AdditionWebService")
@XmlSeeAlso({ObjectFactory.class})
public interface AdditionWebService {

    @WebMethod
    @Action(input = "http://service/AdditionWebService/deleteTwoRequest", output = "http://service/AdditionWebService/deleteTwoResponse")
    @RequestWrapper(localName = "deleteTwo", targetNamespace = "http://service/", className = "generatedSource.com.tanmoy.mypackage.DeleteTwo")
    @ResponseWrapper(localName = "deleteTwoResponse", targetNamespace = "http://service/", className = "generatedSource.com.tanmoy.mypackage.DeleteTwoResponse")
    @WebResult(name = "return", targetNamespace = "")
    public int deleteTwo(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1
    );

    @WebMethod
    @Action(input = "http://service/AdditionWebService/addTwoRequest", output = "http://service/AdditionWebService/addTwoResponse")
    @RequestWrapper(localName = "addTwo", targetNamespace = "http://service/", className = "generatedSource.com.tanmoy.mypackage.AddTwo")
    @ResponseWrapper(localName = "addTwoResponse", targetNamespace = "http://service/", className = "generatedSource.com.tanmoy.mypackage.AddTwoResponse")
    @WebResult(name = "return", targetNamespace = "")
    public int addTwo(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1
    );
}
